### ISSUE TITLE
Could not find package jwcobb/tevo-harvester with stability stable.

### ISSUE THREAD

**Issue by stojko75** [jwcobb/tevo-harvester#12]
After running `composer create-project jwcobb/tevo-harvester  --prefer-dist`

I received following error:

```
[InvalidArgumentException]
Could not find package jwcobb/tevo-harvester with stability stable.
```
I tried with minimum-stability:dev but with no success ?!

**Comment by jwcobb** [comment]
Turns out I never submitted this to Packagist. I've submitted and turned on the update webhook. Try again and let me know if you have any issues.
