### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by stojko75** [jwcobb/tevo-harvester#13]
Hi, 

I have succeed to install and run tevo-harvester. Everything works fine from the web console. I see tables, and i updated them. Problem is when I try to update them from console. I receive following error:

```
php artisan harvester:update events  --action=active 

[GuzzleHttp\Command\Exception\CommandException]
Error executing command: cURL error 60: SSL certificate problem: self signed certificate in certificate chain

[GuzzleHttp\Exception\RequestException]
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

[GuzzleHttp\Ring\Exception\RingException]
cURL error 60: SSL certificate problem: self signed certificate in certificate chain
```
I have newest `certs.pam` file and directive in php.ini `curl.cainfo` is pointing to the file `certs.pam`. 
I have no problem when using ticketevolution-php which also use guzzle!?

What else can be problem?

**Comment by jwcobb** [comment]
What version of PHP and cURL?

**Comment by stojko75** [comment]
PHP Version 5.5.12
```
cURL support 	enabled
cURL Information 	7.36.0
Age 	3
Features
AsynchDNS 	Yes
CharConv 	No
Debug 	No
GSS-Negotiate 	Yes
IDN 	Yes
IPv6 	Yes
krb4 	No
Largefile 	Yes
libz 	Yes
NTLM 	Yes
NTLMWB 	No
SPNEGO 	Yes
SSL 	Yes
SSPI 	Yes
TLS-SRP 	No
Protocols 	dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host 	x86_64-pc-win32
SSL Version 	OpenSSL/1.0.1g
ZLib Version 	1.2.7
libSSH Version 	libssh2/1.4.3 
```

**Comment by jwcobb** [comment]
Harvester uses ticketevolution-php so I can't understand how you don't have problems when using ticketevolution-php unless there is something different.

We've seen some SSL issues before and it is usually when someone is using an outdated version of OpenSSL. Since yours is from mid-2014 I would suspect that your OpenSSL needs to be upgraded.

**Comment by stojko75** [comment]
Ok. I will try and let you know.

**Comment by stojko75** [comment]
After few hours of struggle and troubleshoot I finally solved this problem. My environment is Win with wamp. It turned out that php on CLI use different `php.ini` then Apache php?! One `php.ini` is located in `C:\wamp\php\php5.5.12` and other is located at `C:\wamp\bin\apache\apache2.4.9\bin`. When setting` curl.cainfo` directive, it must be set on **both location** if we use it from web and console.  
I hope this can help someone .
